### ISSUE TITLE
您好，提示当前用户录入中，INFO  0 (wish), 0 (do),0 (collect) movie loaded in 2479 ms

### ISSUE THREAD

**Issue by wang-xiaowu** [mythsman/hexo-douban#128]
目前4个配置项均无内容生成，且提示`INFO 0 (wish), 0 (do),0 (collect) xxx loaded in xxx ms`

nodejs: 17
hexo: 6.3
hexo-douban: 2.2.1
配置：
```
douban:
  id: xxx
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: '虽然岁月如流什么都会过去，但总有些东西发生了就不能抹杀。——王小波'
    quote: '信息摘自豆瓣'
    option:
      comments: false
  movie:
    path: movies/index.html
    title: '希望是美好的，也许是人间至善，而美好的事物永不消逝。——《肖申克的救赎》'
    quote: '信息摘自豆瓣'
    option:
      comments: false
  game:
    path: games/index.html
    title: '这里是死寂之城。这里是表里不一的世界。这里是由恶魔支配的邪恶空间。欢迎你们，来到这一片寂静的沉默之丘。——《寂静岭》'
    quote: '信息摘自豆瓣'
    option:
      comments: false
  song:
    path: songs/index.html
    title: '春天的花开秋天的风，以及冬天的落阳，忧郁的青春年少的我，曾经无知的这么想。——《光阴的故事》罗大佑'
    quote: '信息摘自豆瓣'
    option:
      comments: false
  timeout: 10000
```
我使用github-action构建的
