### ISSUE TITLE
现在是存在风控问题 又无法爬取数据了吗？

### ISSUE THREAD

**Issue by kuole-o** [mythsman/hexo-douban#131]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本。

如疑似遇到 bug ，请提供当前的 hexo 版本、豆瓣ID、以及当前使用的浏览器等信息。  
  
我的环境信息如下：
```json
"hexo": "^6.3.0",
"hexo-douban": "^2.2.1",
"hexo-theme-butterfly": "^4.8.5"
```
  
另外，node.js 是 `16.x`。我的豆瓣ID是：178018128   插件配置如下：
```yml
douban:
  id: 178018128
  builtin: true
  item_per_page: 10 #每页展示的条目数，默认 10 
  meta_max_line: 4 #每个条目展示的详细信息的最大行数，超过该行数则会以 "..." 省略，默认 4 
  movie:
    title: '电影'
    quote: '每一场电影，都是穿越时空的对话。'
    path: movies
    option: 
  timeout: 10000 
```

昨晚第一次装上插件，hexo 日志还会提醒“新用户 已提交”之类的，然后直到今天，一直页面是空的，本地预览也没数据。所以想问问，是插件服务器异常吗
