### ISSUE TITLE
通过侧栏进入页面 刷新才会显示内容 直接转到该路径没问题

### ISSUE THREAD

**Issue by reinshift** [mythsman/hexo-douban#132]
### 网站：<https://reinshift.cn> 
&emsp;&emsp;您好，想请问一下这个问题，首先我看到了#108中的问题可能和我类似，按照该博主设置pjax参数后发现依然没有解决，而我又是个刚建站不久的小白，不具备相关知识qwq，遂再次麻烦您指教
- 站点配置文件：
```
#douban
douban:
  id: 216328359
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  #book:
    #title: 'This is my book title'
    #quote: 'This is my book quote'
  movie:
    path: movies/index.html
    title: '我与电影'
    quote: '一部好电影如若触动了你的灵魂，你一生的轨迹就有可能因此发生变化。'
  #game:
    #title: 'This is my game title'
    #quote: 'This is my game quote'
  timeout: 10000 
```
- 主题配置文件：
```
menu:
  movies: /movies/ || fa fa-film

pjax: 
  enable: true
  exclude: 
  - /movies/
```
从网站侧栏进入该页面：
<img width="985" alt="屏幕截图 2023-05-19 165358" src="https://github.com/mythsman/hexo-douban/assets/87841481/bf8d885c-6905-4c4f-9c11-f32447594bd9">

刷新后：
<img width="963" alt="屏幕截图 2023-05-19 165405" src="https://github.com/mythsman/hexo-douban/assets/87841481/b79561f4-9e6d-441c-aaee-92f2d699291e">

感谢开发者的插件 good work: )
