### ISSUE TITLE
用户ID输入错误

### ISSUE THREAD

**Issue by AlexHaijiaZhu** [mythsman/hexo-douban#167]
node 版本: LTS（20）

hexo 版本:7.1.0

hexo-douban 版本: 2.2.6

douban id : 34533835

问题描述:
![image](https://github.com/mythsman/hexo-douban/assets/15796782/88dc7b14-8477-4d95-afd6-e2d08eb426cb)
使用 [Hexo-Action](https://github.com/AlexHaijiaZhu/hexo-action) 自动部署，显示 _用户ID输入错误_

是从hexo 5 ，hexo-douban 1.1.3 升级上来的。之前一直正常。

**Comment by mythsman** [comment]
看下配置文件，应当是 douban id 配置的不对：
```yaml
douban:
  id: 111111
  builtin: false
  item_per_page: 10
  ....
```

**Comment by AlexHaijiaZhu** [comment]
![image](https://github.com/mythsman/hexo-douban/assets/15796782/2cca35db-6285-4c9f-84f4-5065ddd7732c)
获取的豆瓣ID应该是正确的。在_config中的设置也应当是正确的。

使用的配置如下：
```
##### douban
douban:
  user: 34533835
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: 'Here is my book list'
    quote: '要么旅行，要么读书，身体和灵魂必须有一个在路上。'
    option:
  movie:
    path: movies/index.html
    title: 'Here is my movie list'
    quote: '生活的全部，它行动的整体，乃是一部自然、生动的电影。'
    option:
#  game:
#    path: games/index.html
#    title: 'This is my game title'
#    quote: 'This is my game quote'
#    option:
#  song:
#    path: songs/index.html
#    title: 'This is my song title'
#    quote: 'This is my song quote'
#    option:
  timeout: 30000 
```
