### ISSUE TITLE
关于豆瓣电影页面无法正常显示title的问题

### ISSUE THREAD

**Issue by gmh1627** [mythsman/hexo-douban#186]
node 版本: v18.17.0

hexo 版本:  7.3.0

hexo-douban 版本: 2.3.6

douban id : 258576743

问题描述: 我的配置如下：
```
douban:
  id: 258576743
  builtin: true
  movie:
    title: "Movies"
    quote: '豆瓣电影个人主页'
    actions:
      - collect
      - wish
```
我希望movies页面的标题显示为Movies
![image](https://github.com/user-attachments/assets/83c21655-722e-4449-b214-b8cd9c9b0c87)
而不是和主页的标题一样，显示为Maohang Gao's Blog，请问还应该如何修改？我使用的是butterfly主题，上面的截图是前段时间配置的结果，今天重新配置就显示为Maohang Gao's Blog了。
谢谢！
