### ISSUE TITLE
quote 样式显示问题

### ISSUE THREAD

**Issue by Michael728** [mythsman/hexo-douban#54]
如下是我配置：
```
douban:
  user: 51517255
  builtin: true
  movie:
    title: '观影'
    quote: <div class="note success no-icon"><p>You got a dream, you gotta protect it. People can't do something themselves, they wanna tell you you can't do it.If you want something, go get it. --《当幸福来敲门》</p></div>
```

为了修改 quote 的默认效果，我用如上方式写的，但是显示的效果不符合预期：

![image](https://user-images.githubusercontent.com/8510410/57980310-7c26ac80-7a5c-11e9-8d72-536db364e04b.png)

我观察博主的显示效果是这样的，比较符合预期：

![image](https://user-images.githubusercontent.com/8510410/57980316-93fe3080-7a5c-11e9-9089-e31ae1218f7a.png)
